route:
  username: indexlm
  password: indexlm

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL:118.89.237.99:13450}/${MYSQL_DATABASE:lecare_cloud_db_v2}?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: ${MYSQL_USERNAME:cloud_user}
    password: ${MYSQL_PASSWORD:w6TIsXDPGB3azvxdu/vF}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        watchDelay: 30000 #每30s发现服务 并且配置路由信息
        server-addr: ${NACOS_ADDRESS:127.0.0.1:8848}
        namespace: ${NACOS_NAMESPACE:lecare-develop}
        heart-beat-timeout: 20
        heart-beat-interval: 60
    gateway:
      httpclient:
        #默认为毫秒单位 connect-timeout 默认为45s
        connect-timeout: 5000
        #点进源码可设置不同单位，我这里设置为5s
        response-timeout: 5s
        pool:
          max-idle-time: 10000
          max-connections: 30
      enabled: true  #希望启用网关
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
          lower-case-service-id: true #开启小写验证，默认feign根据服务名查找都是用的全大写
      default-filters:
        - StripPrefix=1
        - name: Retry
          args:
            retries: 3 #重试次数
        - name: Hystrix
          args:
            name: myfallback
            fallbackuri: forward:/fallback/default
      routes:
        # 认证
        - id: service-auth
          uri: lb://service-auth
          predicates:
            - Path=/auth/**
